---
namespace: redhatinsighs
name: insights
version: 0.3.0
readme: README.md
authors:
- Will Tome (@wtome)
description: Ansible Collection for Red Hat insights
repository: https://github.com/wenottingham/ansible-collection-insights.git
build_ignore:
- galaxy.yml.j2
- release.yml
- .gitignore
- changelogs/.plugin-cache.yaml
- tests/output
license:
- Apache-2.0
